### PR TITLE
fix: fix declarations

### PR DESCRIPTION
**Pull request by whxaxes**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Fix mistake of declarations, and add unittest for types.

### CODE REVIEW

**Comment by fengmk2** [comment]
@whxaxes ci fails

**Comment by whxaxes** [comment]
image

Seems mocha doesn't support node-4 anymore, I delete node-4 from travis.yml

**Comment by whxaxes** [comment]
ci passed

**Comment by fengmk2** [comment]
1.1.2

**Pull request merged**
